### ISSUE TITLE
What is this line of code's function? Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [Louis-udm/VGCN-BERT#1]
这行代码的作用是？

![image](https://user-images.githubusercontent.com/4702353/81358510-51b87e00-9109-11ea-8c7f-eb63e7af3d2c.png)

```
vocab_input=gcn_swop_eye.matmul(words_embeddings).transpose(1,2)
```
`gcn_swop_eye` is the gcn one-hot ids.
 `words_embeddings` is from the bert ids.

Thank you very much. 

@Louis-udm 
@Xiang-Pan

**Comment by Louis-udm** [comment]
The graph embedding calculates for every embedding dimension, this is for keeps the embedding dimension size.
