### ISSUE TITLE
prepare_data

### ISSUE THREAD

**Issue by xdo00** [Louis-udm/VGCN-BERT#13]
run prepare_data.py
for i in range(vocab_size):
    norm=np.linalg.norm(vocab_tfidf.data[i])
    if norm>0:
        vocab_tfidf.data[i]/=norm

vocab_adj_tf=vocab_tfidf.dot(vocab_tfidf.T)

TypeError: Expected list, got numpy.ndarray

请问是哪里的问题呢

**Comment by pervaizniazi** [comment]
Hi,
How did you solve it? I am getting the same problem.

**Comment by goonmeet** [comment]
You can try:

vocab_adj_tf=vocab_tfidf.dot(**np.array(**vocab_tfidf**)**.T)

**Comment by pervaizniazi** [comment]
I downgrade scipy that fixed the issue.

**Comment by nathanchen0618** [comment]
> I downgrade scipy that fixed the issue.

This works. I downgrade scipy version from 1.6 to 1.2.
