### ISSUE TITLE
RuntimeError: expected scalar type Float but found Double

### ISSUE THREAD

**Issue by dinaYounes** [Louis-udm/VGCN-BERT#19]
Hello, 
Thank You for the project you uploaded 
I am getting the following error. 
Any idea how to fix it?? 
Any fast reply would be very appreciated!!
Thank You and Best Regards,
![Capture12345](https://user-images.githubusercontent.com/79286235/115169423-a2c94400-a0c6-11eb-9834-6cceb3405e4d.PNG)

**Comment by noghte** [comment]
You can change line 341 to:
loss = F.cross_entropy(logits.view(-1, num_classes), label_ids, loss_weight.float())
I made a pull request for this fix: 
https://github.com/Louis-udm/VGCN-BERT/pull/20
