### ISSUE TITLE
Can not understand the shape of this tensor. Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [Louis-udm/VGCN-BERT#2]
![image](https://user-images.githubusercontent.com/4702353/81360080-7ca4d100-910d-11ea-8703-24763e8dd3db.png)

```
gcn_vocab_out = self.vocab_gcn(vocab_adj_list, vocab_input)
```
`gcn_vocab_out`'s shape is [batch_size, bert_embedding_dim, gcn_embedding_dim]

What does this tensor or shape represent?

Thank you very much.
@Louis-udm 
@Xiang-Pan

**Comment by Louis-udm** [comment]
It means graph representation for every embedding dimension after vgcn.
