### ISSUE TITLE
Why gcn_embedding_dim can become part of the bert sequence? Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [Louis-udm/VGCN-BERT#3]
```
MAX_SEQ_LENGTH = 200+gcn_embedding_dim 
```
感觉gcn_embedding_dim这维是gcn输出的每个word的最后向量表示，为何能和bert输入的sequence_len这维concat呢

Thank you very much.
@Louis-udm 
@Xiang-Pan

**Comment by Louis-udm** [comment]
Every graph embedding keep the shape of word embedding.
